apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: s3-proxy
  namespace: flux-system
spec:
  targetNamespace: pipeline
  releaseName: swift
  chart:
    spec:
      chart: s3-proxy
      sourceRef:
        kind: HelmRepository
        name: radar-base
        namespace: flux-system
  interval: 1h
  install:
    remediation:
      retries: -1
  
  # https://github.com/bitnami/charts/blob/master/bitnami/minio/values.yaml
  valuesFrom:
    - kind: Secret
      name: cluster-secrets
      valuesKey: S3_ACCESS_KEY
      targetPath: s3.identity
    - kind: Secret
      name: cluster-secrets
      valuesKey: S3_SECRET_KEY
      targetPath: s3.credential
    - kind: Secret
      name: cluster-secrets
      valuesKey: S3_ACCESS_KEY
      targetPath: target.identity
    - kind: Secret
      name: cluster-secrets
      valuesKey: S3_SECRET_KEY
      targetPath: target.credential
    - kind: Secret
      name: cluster-secrets
      valuesKey: S3_ENDPOINT
      targetPath: target.endpoint
  values:
    replicaCount: 3
    target:
      provider: s3
    

