# h/t https://github.com/Pumba98/flux2-gitops/blob/70753b77281cd3fa5b417f7910708dce488f430e/apps/all/weave-gitops/helm-release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 5m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.8
      sourceRef:
        kind: HelmRepository
        name: weave
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: cluster-secrets
      valuesKey: WEAVE_GITOPS_PASSWORD_HASH # echo -n $PASSWORD | gitops get bcrypt-hash
      targetPath: adminUser.passwordHash
  values:
    adminUser:
      create: true
      username: admin
    ingress:
      enabled: true
      annotations:
        cert-manager.io/issuer: letsencrypt-staging
        cert-manager.io/issuer-kind: ClusterIssuer
      hosts:
        - host: gitops.${CLUSTER_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - gitops.${CLUSTER_DOMAIN}


