apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: orion-db-auth
    namespace: pipeline
stringData:
    username: ENC[AES256_GCM,data:0ru/Trl2LcE=,iv:rE8FNsojtOz2gtZ6iUwnYHKV4oLhhdEJzxh+62Meexo=,tag:rbdixt4u2DY8q6p9hCnkcQ==,type:str]
    password: ENC[AES256_GCM,data:swq11TMV0wNedT8=,iv:FE+Yllvdf1aJG61eBGTf0+DWTywMyjItPUdinWJ7SiI=,tag:vNhJY1zEl7rn8gyImKA2Vg==,type:str]
    #ENC[AES256_GCM,data:DjExj7p0z53ascZAJytcAUiFHRIO8HsxL0NQ6SIHbg==,iv:6WMeBHeoRFDMwMpK73sw94mFxmcNt/icbGXWY9mzZvw=,tag:cQWrjXXohRBFJbrE8Rtw+A==,type:comment]
    connection-string: ENC[AES256_GCM,data:0cYUEWjUWLzTRjxp9w+k/+G9KiTNOJkrV1uZd43gM1ExV4cN3/7F/WTonXt9IB5KJ8A2JxO+SkdSmuFwkNhk1PjlIx+A8xxE3cy8pHog+LY=,iv:q/B+zZ974NlpZhRdtk2W44wrdFUwaf4wZrKnDdPyS2s=,tag:vBdTYy4sViiNpdR80aGBDg==,type:str]
    #ENC[AES256_GCM,data:VWUrdcSRc7PeIjIsSuYncB3JJB/q8bZNzd0VgP7QZsBywlPJLt0Qh+gNX12iFLWkEgd11yKNogqBlhiey5Db4GmB7Sn8FSjZoFWA+pR0Dzg1bF8d3629L8lsv3zYqUJBP4xfrYzQ1l3aCpYR1g==,iv:dXrAG7X5lwUx1W5Jgf3a9k5bhT6gRhMpS4WsNQMYhpM=,tag:kix8bqqF8UQTFwYA5NTtqg==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xftjgmm59hc7up45dq94a4uj025htlm5mqa802zhtyx6hynsnd5sdhn357
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISksyeTZWVEE2Skd6QW5P
            UmpOeGp6Mk1mS0ZzcHhWQ3d4OEJaVGo1d1c4CktnSVVuOXVhdEI5NWVPUWxwVlUz
            ZW02QXg2KzBlV3BNOFl1bHNpN09ZQTAKLS0tIG1vSFhqVWhrdG1NRURCM1lqcU8y
            R3VVRVRhVUFtdVZvMnJLalZGczBXWTgKWxlT+RywRc+UAnF11xMa0mLm0YyhPBOe
            iZ1WqiHoHop8QDp6yV7/UBepT93UxuGqNOG7qK42aWpxnu/KnKYECw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-11T18:22:37Z"
    mac: ENC[AES256_GCM,data:f87zKZI1q0LnjtlXz8hCqvEdW0fb0/IR9dAEf4xYS828mSJ9qceOaCm1EZxUHbwC2ewOd0aygJ08f6Pq1Sa/d/n9pLUuKEhRMBWZeopp/qv65uckz6bKZ3yaBo/y3mDrRqpLeanCcmYpdJKQ4lNlWbU7AHcy6phEdLabJrnEeMM=,iv:DsQjR7HYWCKUp55ARj2nzJWeh/bG5vmMe+NYhDC+kWw=,tag:LoU4dzhZ9WRmO4+WnjzG+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
