apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cnpg
  namespace: flux-system
spec:
  url: https://github.com/cloudnative-pg/cloudnative-pg.git
  ref:
    tag: v1.18.0
  ignore: |
    # exclude all
    /*
    # include deploy crds dir
    !/config/crd
  interval: 6h
  timeout: 60s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cnpg-crds
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  path: ./config/crd
  prune: false
  wait: false
  sourceRef:
    kind: GitRepository
    name: cnpg