apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: api-runnerdeploy
  namespace: api
spec:
  replicas: 1
  template:
    spec:
      repository: Refugee-Law-Lab/api
      env:
        - name: ARC_DOCKER_MTU_PROPAGATION
          value: "true"