apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hasura
  namespace: flux-system
spec:
  targetNamespace: api
  releaseName: hasura
  chart:
    spec:
      chart: ./charts/hasura
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: -1
  
  valuesFrom:
    - kind: Secret
      name: global-secrets
      valuesKey: API_DATABASE_CONNECTION_STRING
      targetPath: hasura.database.connection.string
    - kind: Secret
      name: cluster-secrets
      valuesKey: HASURA_ADMIN_SECRET
      targetPath: hasura.adminSecret.password

  values:
    image:
      tag: v2.13.1
    hasura:
      debug: "true"
      console:
        enable: "true"