apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hasura
  namespace: flux-system
spec:
  targetNamespace: api
  releaseName: hasura
  chart:
    spec:
      chart: ./charts/hasura
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  
  valuesFrom:
    - kind: Secret
      name: global-secrets
      valuesKey: API_DATABASE_CONNECTION_STRING
      targetPath: hasura.database.connection.string
    - kind: Secret
      name: cluster-secrets
      valuesKey: HASURA_ADMIN_SECRET
      targetPath: hasura.adminSecret.password

  values:
    image:
      tag: v2.13.2
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/issuer: letsencrypt-staging
        cert-manager.io/issuer-kind: ClusterIssuer
        # external-dns.alpha.kubernetes.io/target: somecloudflaretunnel.rllp.ca
        # external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      hosts:
        - host: api.rllp.ca
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
       - secretName: hasura-tls
         hosts:
           - api.rllp.ca
    hasura:
      debug: true
      console:
        enable: true
      extraEnv:
        - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
          value: anonymous