apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  targetNamespace: external-dns
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    domainFilters:
      - rllp.ca
    provider: cloudflare
    cloudflare:
      proxied: false
    policy: sync
  valuesFrom:
    - kind: Secret
      name: global-secrets
      valuesKey: CLOUDFLARE_EMAIL
      targetPath: cloudflare.email
    - kind: Secret
      name: global-secrets
      valuesKey: CLOUDFLARE_API_KEY
      targetPath: cloudflare.apiKey
    - kind: ConfigMap
      name: cluster-config
      valuesKey: CLUSTER_NAME
      targetPath: txtOwnerId
      optional: true