apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:u2SGjMoj0tBQcximNeS9RlSwEIdA0w==,iv:+eanrfnyqyBAlpJe6cZJz/7eyM5m5+b8aB/lrBG6nsM=,tag:gJyiCVpeHr6JsqYaOknV8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xftjgmm59hc7up45dq94a4uj025htlm5mqa802zhtyx6hynsnd5sdhn357
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaWJQZGM0WTZWY2ZLTkVx
            RGRscTBBZG1sYkJYOHErZmQwUm1YbzB4NERFCnk5VkZnSWVXWU1hOFlsS2lVN0lP
            MU1Vais2ekNwZVJaZE9wN0ttL3lPQkEKLS0tIDF4eG1McG5wcW9DTWU2bGhSOE9m
            cHNCa2FxRUZ4RDFjOUpjeEUrdUpiN3MKWOljdcCezKww3nQzggwfcPuKECeR4i5R
            HCrUG0vmnZeKCBnslbttszeABHoYneomIvB+A9X4c8m+VVAcuDSalA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-13T20:36:11Z"
    mac: ENC[AES256_GCM,data:BmK/lNjPCFCoEQUkHUbi8XxQo/LDJLFAinei3t+uXbYL3QhtcwpYsOB+b9Ys/Xwjz/krCcwL2hmEfShdJOvck+Rl5h+VE2L3/UmzOcbHAquXWy9A9jRdvnBnKM/A72pTqrh7AZYP5BCV/1nJ9cK6P5ybQv+JyEq2M3l9yOrsgzE=,iv:4ZPlsLfFFZ9zB1dkemxrBlBeOi8NAMROURTgzm13hUc=,tag:vS1KSct0i3/acqL8bSLAKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
