apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:u2SGjMoj0tBQcximNeS9RlSwEIdA0w==,iv:+eanrfnyqyBAlpJe6cZJz/7eyM5m5+b8aB/lrBG6nsM=,tag:gJyiCVpeHr6JsqYaOknV8A==,type:str]
    #ENC[AES256_GCM,data:vnHrdxjfcDFINQna+WttaXbb8rUiiMZSREqbA486JX6fRMJmvDGU3uemGA==,iv:pfVcgNlaifTVnU0qPQl3lW6irthOE4/iJxoAndV+yDk=,tag:9Zq6z6NZWH17fCMKdzBpZQ==,type:comment]
    WEAVE_GITOPS_PASSWORD_HASH: ENC[AES256_GCM,data:g/Y6Nd8l7cQl0bz4lIbIh++uVx4bL6LarVmFLGwaVqsoP+sVmoGfjY7bNp6EZthWhGT5zyl3puaJeyhs,iv:BbN1GUtrdm+DheTdXfK+1vWNHuOegv3U5SArq7l8scQ=,tag:nLR3ZfT6wXP8fOwp9GUkLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xftjgmm59hc7up45dq94a4uj025htlm5mqa802zhtyx6hynsnd5sdhn357
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaWJQZGM0WTZWY2ZLTkVx
            RGRscTBBZG1sYkJYOHErZmQwUm1YbzB4NERFCnk5VkZnSWVXWU1hOFlsS2lVN0lP
            MU1Vais2ekNwZVJaZE9wN0ttL3lPQkEKLS0tIDF4eG1McG5wcW9DTWU2bGhSOE9m
            cHNCa2FxRUZ4RDFjOUpjeEUrdUpiN3MKWOljdcCezKww3nQzggwfcPuKECeR4i5R
            HCrUG0vmnZeKCBnslbttszeABHoYneomIvB+A9X4c8m+VVAcuDSalA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-14T00:27:32Z"
    mac: ENC[AES256_GCM,data:Gpx1LFK7vURb9DP/9qvIJi1zUVHRaNbeP6s050htJhQAHmG99QcbnhovhA0yITBmydfJOupHV2hP9qFjHCJq/DDVX0H/wlG6OK2GHDmCumSGaDAoGzBJhgxg6hD42vYNr0kqjb7cTRwYjjfGL4QY8JgrN+cWRRugZAUEMN3tcLo=,iv:9MdQvMyeQz538cdrLNBF2g+/aL4uqR/RW8dwdpb2abk=,tag:WuMtlsTWSHXxSOcUaBQUcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
