apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  targetNamespace: monitoring
  interval: 5m
  chart:
    spec:
      version: "41.x"
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 60m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    alertmanager:
      enabled: true
    prometheus:
      prometheusSpec:
        retention: 24h
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        podMonitorNamespaceSelector: {}
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
    ingress:
      enabled: true
      annotations:
        cert-manager.io/issuer: letsencrypt-staging
        cert-manager.io/issuer-kind: ClusterIssuer
      hosts:
        - host: monitoring.${CLUSTER_DOMAIN}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
       - secretName: monitoring-tls
         hosts:
           - monitoring.${CLUSTER_DOMAIN}