apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cloudflare
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: master
  url: https://github.com/cloudflare/argo-tunnel-examples
  ignore: |
    # exclude all
    /*
    # include chart
    !/helm/cloudflare-tunnel

