apiVersion: v1
kind: Secret
metadata:
    name: global-secrets
    namespace: flux-system
stringData:
    API_DATABASE_CONNECTION_STRING: ENC[AES256_GCM,data:yrdItfpQ9mOVSg4DK7VGdAULJLDki2OtZvaroItj8Luf5fnOQTLuvOtXT1f1KjaC848U+6avoHnYQBxt+kehmOKrtjNeRWOiaqAIprQ7uP4PAFEpheiu,iv:PjXIhatOI/DLZ0KmWNBV6TCPI1r2uSakV7McZFSV2J0=,tag:MYcDBJoJjvXI7qrln907Mg==,type:str]
    CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:yszd4eiyyZyA7BVssUGOfv5kCpr6Xvj4N9xI9BbI7bs=,iv:EALtKoyEHguyvEOy7E+64WA3bc8kkhr2WRhXjQSLF7I=,tag:8qbVgU4Qmg85v15jn4CoEw==,type:str]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:tjQrOx4tjy9bxXWekJ0eUI6s9NHo7u62G4HY,iv:UFcHaBsS112L+7rJklBLdQk3mRpFhaZT/N94hkB2t94=,tag:N49SU69KK+rloN17tTvA1A==,type:str]
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:wOpq2ymVj0UIAMa4yXhjQVRlDNdjv0mKBuuJ+FSWI53nbMZ2qg==,iv:fBoeYlYwQ1cyqfCsdXERi7B0/i6BNXssRB/I4cIEtIM=,tag:Ina/ivKPecvALPRjeOvzhw==,type:str]
    GH_PAT_ARC: ENC[AES256_GCM,data:d3imFkAiCAAyMj3AO04SZzmA79kZFpNkbkrdCKCdUBIIWHDngaXvBw==,iv:WbnbfpS8c/2tQECBqKjSB5N96fYR5ycvn0TWOCKY3Mo=,tag:YZThykxdC3CM2k/gVJaC8w==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:UxXm0Pt61lGq5ngC0S1hMUB8GbYrEINLYonAYG7D/rU=,iv:VlIxuP0ZnCH91j8BPZ8SFdMWQ6SJIkPToVXMkq4Lz+A=,tag:nEcGR4VgU5B+jfVpHCm3zg==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:OgLbFcSRa+l5/Dc0GG/wxWMx2QIV7hZ0cS596WnX66Y=,iv:NNZmtfFTLpKFIkRBAUnanlFY/3CdbSinUZzIqsWtqhM=,tag:FD0oAp1mtJQT0gVGK7wC0g==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:GEg3R1W4jwnCj/5Qll0sH5zWArNNBLzx08QwnlXvzZmeWN81QQawca/cOrTg,iv:mmXhoMh3eJCDRXktxDmLAoe2rfAqGNNwZHyDjkpPcJA=,tag:5Q/0E/f4vOksZRaqDyuuhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xftjgmm59hc7up45dq94a4uj025htlm5mqa802zhtyx6hynsnd5sdhn357
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYjJlZDBSeU8vR294K1pM
            d05QNVc1RFpqbGM2MkpUV0NvbnUzbmR2VDBFCkVtQWtuYkkrb2JmVExobitHbGJQ
            eFIrVEY3THRoQzFYM3pTaGZUMHVqQmcKLS0tIHE1OU02OUVPQXJSTFYweGJkVVhW
            VjRQb3dpRWZ5U1NkUlZaVDFwSTc1YkEKfi0ovJUsGgVb0uSYxj1NNbsANihg8jja
            U6Thx/Fm6k7oaw5Vto11roYEyG4SWGwK0swG0H3s5nvNzMB9nENIXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-06T15:50:45Z"
    mac: ENC[AES256_GCM,data:Chx2PgLyP64XzicMromtkwYr3SMkojnJGnOvxVH7OZx9Zl/USjfJpcX+175HIkI9ftkXjDIl6KbEbIrg9VymNEt3EfGubEnksgWBaSX1X0SjAHdVTLFZ0HvPQ71BRV/hm6UeZf7XjTMhf5e6NhxQQgL7Lpo6efasAFtVksC1gEg=,iv:1WFnIF/R3/1Px4brle4WUs5B9B3cw5vY6Yq1my5NNpQ=,tag:z3q9uJGfbwDMi9gXz3P0lA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
