
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  targetNamespace: cnpg-system
  releaseName: cnpg
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.16.0 # appVersion: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  interval: 1h
  install:
    # createNamespace: true
    remediation:
      retries: 3
    disableWait: true
  upgrade:
   disableWait: true

  values:
    crds:
      create: false